version: "3.9"

services:
  agenda:
    image: agenda:local
    ports:
      - "8501:8501"           # Streamlit UI
      - "8765:8765"           # WebSocket server
      - "8000:8000"           # API REST (opcional para futuro)
    environment:
      - DB_PATH=/data/agenda.db
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_ENABLEXsSRFProtection=false
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8765
    volumes:
      - agenda_data:/data
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role != manager  # Ejecutar en worker nodes
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  agenda_data:
    driver: local