version: "3.9"

services:
  backend:
    image: agenda:latest
    command: ["python", "services/main.py"]  # o "python", "main.py" según tu ruta real
    environment:
      - WEBSOCKET_HOST=backend
      - WEBSOCKET_PORT=8765
      - DOCKER_ENV=true
    ports:
      - "8000:8000"   
      - "8765:8765"   
    networks:
      - agenda_net
    deploy:
      replicas: 1

  frontend:
    image: agenda:latest
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    environment:
      - WEBSOCKET_HOST=backend
      - WEBSOCKET_PORT=8765
      - DOCKER_ENV=true
    ports:
      - "8501:8501"   # Streamlit
    networks:
      - agenda_net
    deploy:
      replicas: 1

networks:
  agenda_net:
    driver: overlay
